// Every sentence the app shows, in English. bn.js holds the same names in Bangla.
// A function takes figures that are already written out ("৳1,771", "Sun, 23 Aug") and puts them in a sentence.
// Plain words on purpose: a customer should understand each line on first read.

const days = (n) => (n === "1" ? "1 day" : `${n} days`);

export default {
  days,
  fromNow: (n, raw) => (raw <= 0 ? "today" : raw === 1 ? "tomorrow" : `in ${n} days`),

  frame: {
    tagline: "See a shortfall before it happens",
    synthetic: "Synthetic data",
    screens: "Screens",
    language: "Language",
    tabs: { home: "Home", forecast: "Forecast", actions: "Actions", ask: "Ask", model: "Model" },
    connected: (count) => `Connected · ${count} customers`,
    connecting: "Connecting to the server",
    unreachable: "Server not reachable",
  },

  connection: {
    connecting: "Connecting",
    starting: "Starting the server",
    noAnswer: (address) => ["No answer yet from ", address, ". On a free host the server sleeps when nobody visits and needs about a minute to wake up."],
    trying: "Trying again every few seconds.",
    waited: (seconds) => ` Waited ${seconds} seconds so far.`,
    failed: "The server did not answer",
    failedText: (address) => ["Nothing answered at ", address, ". Check that the server is running there, then try again."],
    tryAgain: "Try again",
  },

  state: {
    loading: "Loading",
    forecastFailed: "The forecast could not be loaded",
    explanationFailed: "The explanation could not be loaded",
    resultsFailed: "The test results could not be loaded",
    tryAgain: "Try again",
  },

  context: { today: (day) => `Today is ${day}`, change: "Change" },

  personas: { rider: "Rider", garment: "Garment worker", student: "Student", shopkeeper: "Shop owner", freelancer: "Freelancer" },

  payments: {
    house_rent: "House rent",
    mess_rent: "Mess rent",
    shop_rent: "Shop rent",
    send_home: "Money sent home",
    savings_samity: "Savings group (samity)",
    bike_installment: "Bike installment",
    electricity: "Electricity bill",
    internet: "Internet bill",
    subscriptions: "Subscriptions",
    supplier: "Supplier",
    grocery: "Grocery shop",
    food: "Food",
    pharmacy: "Pharmacy",
    shopping: "Shopping",
    transport: "Transport",
    other: "Regular payment",
  },

  switcher: {
    title: "Demo customer",
    hint: "In a real wallet this is the signed-in customer, today.",
    kind: "Kind of customer",
    customer: "Customer",
    today: "Today is",
    earlier: "One day earlier",
    later: "One day later",
    back: "Back to the demo day",
  },

  status: {
    warning: "Warning",
    noWarning: "No warning",
    allClear: "All clear",
    shortfallTitle: (day) => `You may run short around ${day}`,
    shortfallText: (when, cushion, oneDay) =>
      `That is ${when}. Your balance may drop below your safety cushion of ${cushion}${oneDay ? ", about one day of your typical spending (rent and other regular payments included)" : ""}.`,
    lowNowTitle: "Your balance is already low",
    lowNowText: (balance, cushion, period) =>
      `You have ${balance} today. That is under your safety cushion of ${cushion} (about one day of your typical spending, rent and other regular payments included). It may stay low for the next ${period}.`,
    recoveringTitle: "Low today, but it should recover",
    recoveringText: (balance, cushion, period) =>
      `You have ${balance} today, under your safety cushion of ${cushion} (about one day of your typical spending, rent and other regular payments included). We expect money to come in, so there is no warning for the next ${period}.`,
    recoveringButPayments: "But the payments you have to make are more than the money we expect. See Safe to spend below.",
    clearTitle: (period) => `No warning for the next ${period}`,
    clearText: (balance, cushion) => `You have ${balance}. That is above your safety cushion of ${cushion} (about one day of your typical spending, rent and other regular payments included).`,
    chance: "chance of running short",
    short: "how much you could be short",
    left: "could be left in your wallet",
    seeActions: "See what you can do",
    why: "Why?",
    seeForecast: "See the forecast",
    rule: (level) => `We warn when the chance is ${level} or more.`,
  },

  safe: {
    title: "Safe to spend",
    aDay: "a day",
    untilIncome: (day, period) =>
      `Spend this much a day and you can still make every regular payment on time until your next income on ${day}, ${period} away.`,
    until: (day, period) =>
      `Spend this much a day and you can still make every regular payment on time until ${day}, ${period} away.`,
    usual: (amount) => `You usually spend about ${amount} a day.`,
    nothing: "Your regular payments and your safety cushion take all the money we expect before then.",
    nothingBy: (day) => `The payments due by ${day} take all the money you have and all the money we expect by then.`,
    nothingYet: (day) => `You have nothing to spend today, and we cannot count on money coming in by ${day}.`,
    how: "How we worked this out",
    tightest: (day, period) => `We check every day of the period. The tightest day is ${day}, ${period} away. This is the sum for that day:`,
    lastDay: (day) => `We check every day of the period. The tightest day is the last one, ${day}. This is the sum for that day:`,
    balance: "You have today",
    income: "Money likely to come in by that day, counted carefully",
    payments: "Regular payments due by that day",
    cushion: "Safety cushion to keep",
    cushionLater: "The safety cushion is counted on the last day of the period, not on this one.",
    savings: "Put aside for your savings goal",
    left: (period) => `Left for ${period}`,
    sum: (left, period, amount) => `${left} over ${period} is ${amount} a day, rounded down.`,
    sumNothing: "Nothing is left, so the safe amount is ৳0.",
    fixed: "This is a fixed formula, not a guess by AI.",
  },

  balance: {
    title: "Balance",
    asOf: (day) => `At the end of ${day}.`,
    cushion: "Safety cushion",
    cushionOneDay: "The least you should keep: about one day of your typical spending, rent and other regular payments included. We warn when your balance may drop below it.",
    cushionDays: (n) => `The least you should keep: about ${n} days of your typical spending, rent and other regular payments included. We warn when your balance may drop below it.`,
  },

  coming: {
    title: "Coming up",
    income: "Income expected",
    none: (n) => `No regular payments are due in the next ${n} days.`,
    daily: "Your income comes in day by day, so no single income day is shown.",
    irregular: "Your income has no fixed day, so none is shown.",
    more: (n) => `${n} more on the Forecast screen`,
  },

  goal: {
    title: "Savings goal",
    intro: "Want to put money aside? Say how much and by when. We take it out of your safe-to-spend amount.",
    amount: "Amount (৳)",
    by: "By",
    set: "Set goal",
    remove: "Remove goal",
    plan: (amount, day, perDay) => `To save ${amount} by ${day}, put aside ${perDay} a day.`,
    effect: (before, after) => `Your safe-to-spend amount goes from ${before} to ${after} a day.`,
    noRoom: "With this goal nothing is left for everyday spending. Try a smaller amount or a later date.",
    invalid: "Enter an amount above zero and a date after today.",
  },

  forecast: {
    title: (n) => `Your balance for the next ${n} days`,
    showActual: "Show what really happened",
    read: "The green line is what we expect. The shaded area shows how much higher or lower it could be.",
    lowest: (day) => `lowest point we expect, on ${day}`,
    cautious: (day) => `lowest point if things go badly, on ${day}`,
    last: (day) => `what we expect on ${day}, the last day`,
    demo: "Demo only: the days after “today” are already in the synthetic data, so the forecast can be compared with what happened. The forecast never sees them.",
    paymentsTitle: (n) => `Regular payments in the next ${n} days`,
    noPayments: "No regular payments were found in this customer's history.",
    paymentsText: (count, total) =>
      `${count === "1" ? "1 payment" : `${count} payments`}, ${total} in all. We find them in the customer's own history: the same receiver, a similar amount, around the same day each month.`,
    incomeDaily: "Income comes in day by day, so no single income day is shown.",
    incomeIrregular: "Income has no fixed day, so none is shown.",
  },

  chart: {
    cushion: (amount) => `Safety cushion ${amount}`,
    warning: (day) => `Warning: ${day}`,
    today: (day) => `Today, ${day}`,
    balance: "Balance",
    expect: "We expect",
    range: "Could be",
    to: (low, high) => `${low} to ${high}`,
    without: "Without the action",
    actual: "Really happened",
    keyExpect: "What we expect",
    keyNarrow: "Likely range (5 times in 10)",
    keyWide: "Wider range (8 times in 10)",
    keyCushion: "Safety cushion",
    keyWithout: "Without the action",
    keyActual: "What really happened",
  },

  actions: {
    title: "What you can do",
    none: "Nothing in this customer's history points to a step that would help. The best thing is to keep spending as low as possible until more money comes in.",
    intro: "Each one saves money or moves a payment to a better day. None is a loan or a paid product. Switch one on to see what changes.",
    names: { keep_to_safe_spend: "Keep to the safe amount", move_payment: "Move a payment", pay_directly: "Pay shops directly" },
    other: "Suggested action",
    keep: (safe, until, usual) => `Keep everyday spending to ${safe} a day until ${until}. You usually spend about ${usual}.`,
    move: (amount, payment, to, from) => `Pay the ${amount} for ${payment} on ${to} instead of ${from}, after your income arrives.`,
    pay: (fees) => `Pay shops straight from your wallet instead of cashing out first. In the past month you paid about ${fees} in cash-out fees.`,
    adds: (amount) => `Leaves about ${amount} more on your tightest day.`,
    eyebrow: "What changes",
    standing: "Where things stand",
    stands: "The warning stands",
    standsText: (day) => `The forecast shows a warning for ${day}, and there is no suggested action to try against it.`,
    nothingNeeded: "Nothing needs to change",
    nothingNeededText: "There is no warning, and no action is suggested.",
    switchOn: "Switch an action on to see what changes",
    switchOnWarned: (day) => `The forecast shows a warning for ${day}.`,
    switchOnClear: "There is no warning right now. An action would still leave more in your wallet.",
    working: "Working it out",
    gone: (several) => `With ${several ? "these actions" : "this action"}, the warning goes away`,
    goneText: (level) => `The chance of running short falls below ${level}, the level at which we warn.`,
    lower: "The warning stays, but the risk is lower",
    lowerText: (several, before, after) => `With ${several ? "these actions" : "this action"}, the chance of running short falls from ${before} to ${after}.`,
    stays: "The warning stays",
    staysText: (several) => `${several ? "These actions help" : "This action helps"} a little, but not enough to remove the warning.`,
    more: "More is left in your wallet",
    moreText: (several) => `There was no warning, and with ${several ? "these actions" : "this action"} there is still none.`,
    now: "Now",
    withIt: (several) => (several ? "With the actions" : "With the action"),
    chance: "Chance of running short",
    lowest: "Lowest balance we expect",
    under: (level) => `under ${level}`,
    chartWith: "The forecast with the action",
    chartPlain: "The forecast as it is",
    failed: (error) => `This could not be worked out: ${error} Switch the action off and on to try again.`,
  },

  ask: {
    whyWarning: "Why this warning",
    whereYouStand: "Where you stand",
    figures: "The figures behind this text",
    figuresNote: "Each figure comes from the forecasting model or a fixed rule. The text contains no number that is not here.",
    facts: {
      balance: "You have today",
      cushion: "Safety cushion",
      alertDay: "First day at risk",
      chance: "Chance of running short",
      gap: "How much you could be short",
      safe: "Safe to spend a day",
      until: "That amount has to last until",
      income: "Next income expected",
      incomeIn: (day, period) => `${day}, in ${period}`,
      payments: "Regular payments to make before then",
      usual: "What you usually spend a day",
      chanceAfter: "Chance with the suggested action",
    },
    questionsTitle: "Ask a question",
    questionsText: "An AI answers using only this customer's figures. An answer is shown only if every number in it is correct.",
    waiting: "Writing an answer. This can take a few seconds.",
    byAi: "Written by AI from the figures above. Every number was checked.",
    unavailable: "The assistant could not give a checked answer just now. The explanation above still holds. Try again in a minute.",
    noAnswer: (error) => `No answer: ${error}`,
    yourQuestion: "Your question",
    placeholder: "Type your question",
    send: "Ask",
    suggested: {
      warning: ["Why do I run short?", "What should I do now?", "How much can I spend each day?"],
      clear: ["Am I safe this month?", "How much can I spend each day?", "When is my next income?"],
    },
  },

  model: {
    title: "How good is the forecast?",
    intro: (trained, from, to, forecasts, customers, unseen) =>
      `The model learned from data up to ${trained}. It was then tested on forecasts made from ${from} to ${to}, days it had never seen: ${forecasts} forecasts for ${customers} customers, ${unseen} of whom it had never seen at all.`,
    synthetic: "All results on this screen come from synthetic data. They show that the method finds the patterns put into that data. They do not show how it would do with real customers.",
    checks: [
      "Beats every simple method at 7, 14 and 30 days",
      "The range holds the real balance about as often as it says",
      "Warnings are better than the simple rule",
    ],
    errorTitle: "Against simple methods",
    errorText: "The error is counted in days of the customer's usual spending: 3.4 means the forecast balance was off by about three and a half days of spending. Lower is better. The further ahead, the harder the forecast.",
    errorCaption: "Error for each number of days ahead, from 1 to 30",
    daysAhead: (n, raw) => (raw === 1 ? "1 day ahead" : `${n} days ahead`),
    modelName: "Model",
    baselines: {
      "same period last month": "Same period last month",
      "average of the last 3 months": "Average of the last 3 months",
      "recent daily average": "Recent daily average",
    },
    colDays: "Days ahead",
    colModel: "Model",
    colBest: "Best simple method",
    colBetter: "Model is better by",
    unseen: (count, low, high, model) => `For the ${count} customers the model never saw, it is still better by ${low} to ${high}. The model: ${model}.`,
    rangeTitle: "Is the range honest?",
    rangeText: "A forecast gives a range, not one number. The range is honest if the real balance falls inside it as often as it claims.",
    meter: (share, target) => [share, ` of real balances fell inside the range meant to hold ${target}`],
    meterWide: "The wider range on the chart, over all 30 days",
    meterNarrow: "The narrower range on the chart, over all 30 days",
    meterNote: "The bar is the share the range really held. The dark mark is the share it is meant to hold.",
    warningTitle: "Early warnings",
    warningText: (period, asked, share) =>
      `The question: on a day when the customer is not short, will they run short in the next ${period}? Out of ${asked} such days in the test, ${share} were followed by a shortfall.`,
    rankModel: "ranking quality of the model (1 is perfect, 0.5 is a coin toss)",
    rankRule: "ranking quality of the simple rule",
    colRule: "Warning rule",
    colCaught: "Shortfalls caught",
    colRight: "Warnings that were right",
    colFalse: "False alarms",
    ruleSimple: "Simple rule: the 3-month average",
    ruleLevel: (level) => `Model, warning at ${level}%`,
    ruleSame: "Model, set to the same false alarms as the simple rule",
    inApp: "used in the app",
    warningNote: (level) =>
      `Caught: the share of real shortfalls that had a warning. Right: the share of warnings that were followed by a shortfall. False alarms: the share of safe periods that got a warning anyway. A lower level catches more and cries wolf more; ${level} was chosen as the balance.`,
    personaTitle: "By kind of customer",
    personaText: "Error 14 days ahead, in days of usual spending, and how the range and the warnings hold up.",
    colCustomer: "Customer",
    colBetterBy: "Better by",
    colInside: "Inside the wider range",
    colRanking: "Warning ranking",
    personaLabels: { rider: "Ride-share rider", garment: "Garment worker", student: "University student", shopkeeper: "Small shop owner", freelancer: "Freelancer" },
    weak: "Weak spots, marked in the table:",
    weakWarnings: (who) => ` warnings are least reliable for ${who}, whose income arrives day by day.`,
    weakRange: (who) => ` The range is too narrow for ${who}, whose income is the hardest to predict.`,
    plural: (label) => `${label.toLowerCase()}s`,
    and: " and ",
    impactTitle: "Does following the advice help?",
    impactText: (customers, from, to) =>
      `We simulated the same ${customers} customers twice over ${from} to ${to}: once as they were, and once keeping to the safe-to-spend amount on every day the app showed a warning. Nobody cut below half of a day's need.`,
    impactWithout: "Without Agam",
    impactWarned: "Following it when warned",
    impactEvery: "Following it every day",
    impactRows: {
      borrowed_per_customer: "Borrowed per customer",
      customers_who_borrowed: "Customers who had to borrow",
      days_with_a_payment_overdue: "Days with a regular payment overdue",
      very_hard_days: "Days with under a quarter of the day's need met",
      hard_days: "Days with under half of the day's need met",
      spending_met: "Share of wanted spending actually spent",
      days_warned: "Days with a warning",
    },
    impactChange: "Change when warned",
    impactRange: (low, high) => `${low} to ${high}`,
    impactPoints: (value) => `${value} pts`,
    impactTakeaways: "What it shows, for customers who followed the warnings:",
    impactFell: (name, before, after) => `${name}: down from ${before} to ${after}.`,
    impactRose: (name, before, after) => `${name}: up from ${before} to ${after}.`,
    impactSame: (name, before, after) => `${name}: no clear change (${before} against ${after}).`,
    impactMoral: "The app does not create money. Where things improve, it is because the customer spent less on the days it warned.",
    impactHalfNote: "The count of days under half includes days a customer chose to spend half.",
    impactNote: "A simulation of customers we wrote ourselves, not a trial with real people. After the first changed day the two runs get different random events, so only totals over all customers mean something.",
    dataTitle: "What the data assumes",
    colIncome: "How income arrives in the data",
    allAssumptions: "Every assumption, in full",
    limitsTitle: "Limits",
  },
};
